# Generated by Django 5.1.1 on 2025-01-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="duration",
            field=models.DecimalField(
                decimal_places=2, max_digits=2, verbose_name="Duration in months"
            ),
        ),
    ]
