# Generated by Django 5.1.1 on 2025-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_goal_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="duration",
        ),
        migrations.AddField(
            model_name="goal",
            name="duration_days",
            field=models.IntegerField(default=0, verbose_name="Duration in days"),
        ),
        migrations.AddField(
            model_name="goal",
            name="duration_months",
            field=models.IntegerField(default=0, verbose_name="Duration in months"),
        ),
    ]
