# Generated by Django 5.1.1 on 2025-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_test_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="qdrant_id",
            field=models.CharField(max_length=255),
        ),
    ]
