# Generated by Django 5.1.1 on 2025-01-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_score_score_score_right_fluency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
