# Generated by Django 5.1.1 on 2025-01-30 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_goal_is_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="learning_module",
        ),
        migrations.DeleteModel(
            name="LearningModule",
        ),
    ]
