# Generated by Django 5.1.1 on 2025-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_learningmodule_feedback_learning_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_attempted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="type_of_quiz",
            field=models.CharField(
                choices=[("A", "Preliminary Test"), ("B", "Module Test")],
                default="A",
                max_length=1,
            ),
        ),
    ]
