# Generated by Django 5.1.1 on 2025-02-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_test_goal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="goal_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.goal",
            ),
        ),
    ]
