# Generated by Django 5.1.1 on 2025-02-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_test_goal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="module_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
