# Generated by Django 5.1.1 on 2025-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_customuser_github_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="feedback",
            field=models.TextField(default=""),
        ),
    ]
