databases:
  - name: amdocs
    plan: free
    databaseName: amdocs
    user: amdocs

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker" 